### ISSUE TITLE
Compilation instructions?

### ISSUE THREAD

**Issue by webspacecreations** [InvisibleUp/uvmac#3]
On Linux (debian-based distro), how the heck are you supposed to compile this code?

**Comment by luciditee** [comment]
I don't own this repo, but I managed to get it to compile on Ubuntu 18.04 with the procedure found in this comment: https://github.com/InvisibleUp/minivmac/issues/4#issuecomment-720167052

Might be worthwhile for @InvisibleUp to make a BUILDING.md or COMPILING.md file to guide users on what's required.

**Comment by fstark** [comment]
Coming from the webpage where the author rants against minivmac, I found it amusing that his fork, which have a stated got to "make the project easier to compile", lacks info on how to compile the project.

I succeeded by doing, ubuntu (procedure in linked comment didn't work exactly):

git clone https://github.com/InvisibleUp/minivmac.git
cd minivmac
( cd src/ && git clone https://github.com/cktan/tomlc99.git )
( cd src/ && git clone https://github.com/graphitemaster/incbin.git )
( cd ./lib/M68K/ && make )
meson builddir
ninja -C builddir

Then, copying a vMac.ROM file in the directory got me a '?' screen (I found hilarious that the main README of this projects shows you what *will* happens when you have no ROM with the future "configuration manager").

No idea how to add a drive...

**Comment by InvisibleUp** [comment]
I think you have the impression that this project is significantly more complete than you think it is. I probably hyped it up way too much on my website and the readme. My sincere apologies about that.

Anyways, yes, you do a recursive clone and run meson. Unfortunately, as part of replacing the CPU core with Mushashi, I broke the floppy drive emulation as the existing Mini vMac code requires a special CPU interrupt hook. In the event I pick this project up again, that's the first thing I would need to fix.

Also, for future reference, my pronouns are she/her/hers.
